before_commands:
    - composer install --no-interaction

filter:
    excluded_paths:
        - Tests/*
        - vendor/*

tools:
    php_changetracking:
        enabled: true
    php_code_coverage:
        enabled: true
    php_sim:
        enabled: true
    php_code_sniffer:
        enabled: true
        config:
            standard: PSR2
    php_cpd:
        enabled: true
    php_mess_detector:
        enabled: true
        config:
            rulesets:
                - codesize
                - controversial
                - design
                - naming
                - unusedcode
    php_pdepend:
        enabled: true
    php_analyzer:
        enabled: true
    php_loc:
        enabled: true
